# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason_for_contacting', models.CharField(max_length=80)),
                ('message', models.TextField(default='')),
                ('send_to_yourself', models.BooleanField(default=False)),
            ],
        ),
    ]
