# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason_for_contacting',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
